/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class makemachine_android_examples_Nati */

#ifndef _Included_makemachine_android_examples_Nati
#define _Included_makemachine_android_examples_Nati
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     makemachine_android_examples_Nati
 * Method:    fakulty
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_makemachine_android_examples_Nati_fakulty
  (JNIEnv *, jclass, jint);

/*
 * Class:     makemachine_android_examples_Nati
 * Method:    improc
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_makemachine_android_examples_Nati_improc
  (JNIEnv *, jclass, jobject);

/*
 * Class:     makemachine_android_examples_Nati
 * Method:    getrot
 * Signature: (Landroid/graphics/Bitmap;)V
 */
JNIEXPORT void JNICALL Java_makemachine_android_examples_Nati_getrot
  (JNIEnv *, jclass, jobject);

#ifdef __cplusplus
}
#endif
#endif
